# Generated by Django 3.1.7 on 2021-03-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='file_id',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='filesdata',
            old_name='data_source_id',
            new_name='data_source',
        ),
        migrations.RenameField(
            model_name='filesdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
