# Generated by Django 3.1.7 on 2021-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0004_auto_20210311_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesdata',
            name='execution_time',
            field=models.IntegerField(default=0),
        ),
    ]
