# Generated by Django 3.1.7 on 2021-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0005_filesdata_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesdata',
            name='user',
        ),
        migrations.AddField(
            model_name='filesdata',
            name='user_name',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
