# Generated by Django 3.1.7 on 2021-03-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataAnalysis', '0006_auto_20210312_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesdata',
            name='execution_time',
            field=models.FloatField(default=0),
        ),
    ]
